services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: hasura
      POSTGRES_PASSWORD: hasura
      POSTGRES_DB: hasura_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  hasura:
    build: .
    restart: always
    ports:
      - "8080:8080"
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://hasura:hasura@postgres:5432/hasura_db
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ADMIN_SECRET: "${NEXT_PUBLIC_HASURA_ADMIN_SECRET}"
      HASURA_GRAPHQL_ENABLE_SUBSCRIPTIONS: "true"
      HASURA_GRAPHQL_JWT_SECRET: '{"type": "HS256", "key": "${NEXTAUTH_SECRET}"}'
    env_file:
      - .env
    depends_on:
      - postgres

volumes:
  postgres_data:
