version: 3
sources:
  - name: default
    kind: postgres
    configuration:
      connection_info:
        database_url:
          from_env: HASURA_GRAPHQL_DATABASE_URL
        headers:
          - name: X-Hasura-User-Id
            value_from_env: HASURA_USER_ID_HEADER
        isolation_level: read-committed
        use_prepared_statements: true
    tables: []
